### PR TITLE
state management of current page

### PR DESCRIPTION
**Pull request by henryStelle**
The current state management of which page is active requires 6 state changes per page change and makes adding css to the active button tricky. This PR presents a solution to both issues. It also leverages flex displays rather than floats to make the coded order of pages in the header clearer.

### CODE REVIEW

**Comment by henryStelle** [comment]
Because the value of `page` can't be enforced with types, would it be better to have a `pageOptions` object like `{ about: 'about', academics: 'academics', ... }` to mitigate potential spelling mistakes/differences down the road?

**Comment by GeorgeShao** [comment]
lgtm
- 6 state changes per page change really isn't a big deal, but if you've already narrowed it down to 1 stage change without adding much complexity, that's good
- the underline is a nice ux addition


> Because the value of `page` can't be enforced with types, would it be better to have a `pageOptions` object like `{ about: 'about', academics: 'academics', ... }` to mitigate potential spelling mistakes/differences down the road?

I don't think that is necessary

**Comment by GeorgeShao** [comment]
Before we merge let's have @brandon-gartner take a look at it

**Comment by brandon-gartner** [comment]
sadge all my work.

anyway seems like its just an improved form of what i did so yeah no issues from me.

**Pull request merged**
